### ISSUE TITLE
[Checklist] 1.20 Port (v3) worldgen tweaks/minor additions 

### ISSUE THREAD

**Issue by cybercat5555** [MoriyaShiine/aylyth#74]
### Mod version (NOT Minecraft version)

1.20.1

### A description of the issue

Summary of worldgen-oriented tweaks, or minor new stuff that isn't major. New worldgen will be its own post, as will new content overall

- [ ] The Sun has Vanished: The "sun" (as in, the custom aylyth sun) does not currently appear in the sky. Also, the time of day should be "paused" with the sun never moving or setting
- [ ] Axis Mundi: At spawn, or roughly in the general area, a Seeping Tree (the one grown from Girasol Seeds) will generate
- [ ] Mud: Edges of all water features are lined with mud, both on the sides and bottoms, with a bit of bleed into the surrounding terrain
- [ ] Tree replacement in Forests: Standard Copse forests no longer contain vanilla Dark Oaks. Instead, they use the custom Aylyth Oaks. 
- [ ] Fix "Oceans"
- [ ] More Diverse terrain: 
 - [ ] Dirt that generates up to 4 layers under grass should be rooty
 - [ ] Rooty dirt can generate in small “blobs” on the ground in any biomes but Clearings and Uplands.
 - [ ] “Dark Podzol” replaces the normal Podzol in Deepwoods-type biomes (texture pending)
 - [ ] Normal Podzol occurs in “veins” (as in, spreading out like veins, see below) in Deepwoods Aylyth biomes. 
 - [ ] Dark Podzol occurs in “veins” in normal Aylyth forest biomes. 
 - [ ] Dark Podzol can generate under trees in normal Aylyth forests, similar to how Podzol works under vanilla big spruce trees.
- [ ] More ambiance sounds
![2024-08-03_14 54 46](https://github.com/user-attachments/assets/a30eb105-6af9-4e58-ac56-0e96538f43df)

### Log or crash report

n/a
