### ISSUE TITLE
[Checklist] New/major worldgen for v3

### ISSUE THREAD

**Issue by cybercat5555** [MoriyaShiine/aylyth#75]
### Mod version (NOT Minecraft version)

1.20.1

### A description of the issue

Summary of new content that is related to worldgen, or significant changes to older stuff. Does not include new content that is not related to worldgen.

- [ ] **Sapstone**: A new decorative series of stone-type blocks, which comes in 4 variants (Amber, Lignite, Opalescent, then default) . The raw version of them also has a large series of CTM types
![sapstone](https://github.com/user-attachments/assets/f5345dba-b789-4612-914d-1e6116e364ef)
![sapstone types](https://github.com/user-attachments/assets/75c139d9-893e-482c-9694-7fa7ab2f4221)
- [ ] **Sapstone** Suite: [textures pending] series of decorative blocks made from Sapstone. Each of the 4 raw types has its own set of deco blocks
- [ ] **Black Well**: A block related to progression. For now just the block itself needs to be added
- [ ] **Black Well Structure**: A "structure" that contains a single Black Well (the only place they may occure), it is important to find these for progression. The structure should generate in any Deepwoods type biome, and it must generate inset into the ground by 1 (so the well actually looks like a natural well, rather than a man-made wishing well). The Large Woody Growths in it should be replaced with small ones 30% of the time, and simply replaced with air 10% of the time. Structure is linked here:
[black well.zip](https://github.com/user-attachments/files/16972036/black.well.zip)
- [ ] **Deep Black Well**: [assets pending] A variant of the standard Black Well, which will be used to summon a boss. It should be set up to accept different bosses, as even though for this there is only 1 boss planned, the idea is future ones will also be summoned with their own Deep Black Wells in their own arenas (see below)
- [ ] **Deep Black Well Yhondyth Enclosure**: [structure pending] The location where the Deep Black Well spawns, allowing one to summon and challange the Yhondyth.
- [ ] **Thorns and Blighted Thorns**: [assets pending] A type of worldgen that can occur rarely in dense biomes, but being very common in a new biome, the Overgrown Deepwoods. Thorns are a multipart that generate in a manner similar to either Biomes O Plenty Thorns or Twilight Forest Thorns, whichever is easier. Has both the multipart type and a standard 2-tall x model. Blighted Thorns do not spawn in dedicated groups, but instead, any normal Thorns has a chance of being replaced with Blighted ones. It however still connects to the normal ones
- [ ] **Assorted Decorators**: [structures pending]: A series of  misc details to flesh out the realm. Tanged masses of woody growths and thorns, remains of giant, ancient stumps, etc. These will be built by hand.
- [ ] **Estantiga Trees Suite**: A new tree with its typical stuff. The tree itself will likely be handed by Santy
- [ ] **Chthonia “trees”**: A "tree" or root-like formations that occurs in a specific underground biome. Vital to progression, a small percentage of the blocks that generate as part of this formation is replaced with a Nephrite-Bearing type. Gen will likely be handed by Santy
- [ ] **Tall Jack O Lantern Mushrooms**: [assets pending] a 2-tall variant of the normal Jack o Lantern mushrooms. Can be found in either Deepwoods biome as well as the Coniferous Copse, but is more common in Coniferous Deepwoods than any other biome. Glows slightly. Can be created by bonemealing normal ones.
- [ ] **Giant Jack o Lantern Mushrooms**: A large type of these, akin to vanilla giant mushrooms. The caps glow. Spawns only in Coniferous Deepwoods (at the same rate of giant mushrooms in vanilla Dark Forests), or can be grown from tall ones using bonemeal. Each block used in this has a chance of dropping a normal version of the mushroom, also like vanilla.
- [ ] **Biome: Petrified Woods**
![image](https://github.com/user-attachments/assets/617e37e1-6359-4ae5-8ec3-d64719bdb233)
- [ ] **Biome: Overgrown Deepwoods**
![image](https://github.com/user-attachments/assets/e51f03ae-c972-4fdd-aecc-be1c65d9bf50)
- [ ] Dendroglyphs: [assets pending] occurs in a pattern similar to how double tall seeps generate, but the top and bottom must match. Involved in documentation, but that is not included here

### Log or crash report

n/a
