### ISSUE TITLE
[checklist] Minor tweaks/rebalances/additions

### ISSUE THREAD

**Issue by cybercat5555** [MoriyaShiine/aylyth#76]
### Mod version (NOT Minecraft version)

1.20.1

### A description of the issue

Summary of tweaks or minor new content that is not related to worldgen. Many of these are rebalances or solutions to issues that arose from running a server with this mod with different progression levels of players. Worldgen and major new content are their own posts

### New Stuff
- [ ] **Custom Soulfire particles**: Called "soul_ember_[x]" Replaces the times we use vanilla soulfire particles, such as for the trail of Rippled Souls (related to the below), Soul Hearths, and so forth. It will have to be tinted in a soulfire colour, as it can be reused for other stuff later. Animated, goes though the textures numerically. 
- [ ] **Ripped Soul Custom Model**: The Ripped Soul entity now has a unique model/animation set, so we can remove the soft dependency on Illuminations
- [ ] **Nephrite Flask**:  [Standard] Flasks are created in a fire ritual using 3 Nephrite and 1 Esstline. Comes in 2 varieties, normal and Blighted (Blighted=normal+blighted thorn; normal=blighted flask+aylythian heart). Each one can be imbibed 6 times before emptied, and applies Instant Health (if normal) or Instant Harming (if Blighted, intended for undead players), and the texture changes on doses left and on what type it is. Refilled at a Soul Hearth at the cost of 1 Pomegranate for a full flask.
- [ ] **Ympe Mush**: Obtained from harvesting Ympe Fruits on trees without the dedicated tools. Recovers the same amount of hunger, but only has a 25% chance of lowing ympeification by 1 stage, and has a 50% chance of applying Wyrded.
- [ ] **Green Pilot Light**
- A new type of Pilot Light that ONLY spawns when a player enters the realm from dying in forest biomes. Using a Seep or an Aylythian Heart will NOT spawn one
- Green pilot lights may be r-clicked on to send the player to aylyth’s world spawn, allowing them to exit from the Axis Mundi if needed
- Toggleable, on by default

### Tweaks/Changes
- [ ] **Wrongmeat Nerf**
- Wrongmeat hearts now have a unique texture and is handled as a different type of heart, allowing other things to interact with it in different ways
- When you gain a meatheart, it is not considered filled. You will need to drink a Nephrite Flask (the type depends on if you’re undead or not) to fill it. They no longer fill naturally nor after respawning. As such, if you lose them in battle, they will remain empty until you use a Nephrite Flask.
- Using a Nephrite Flask will restore Meathearts after it has resorted any missing normal health
- [ ] **Ympe-Related Nerfs**:
- Ympe can no longer be cultivated outside of Aylyth. Doing so will cause any placed saplings to grow into Large Woody Growths with some Small Woody Growths around it
- Ympe Leaves no longer drop Ympe Saplings. They will HAVE to be obtained from slaying various aylythians now, as it better fits the lore and also to make shucking mobs less cheap
- Growth rate of ympe fruits is slower
- Even in aylyth, there is a chance (50%) that single saplings turn into the Woody Growth clusters as detailed above. However, placing 2x2 saplings will always grow into the larger ympe trees (again only in aylyth)
- You must use a Lanceolet or Ympe Dagger to now harvest fruits. Using anything else will create Ympe Mush instead
- [ ] **Shucked Related Nerfs**
- Only Ympe Daggers (not Lanceolet ones) can shuck fruits, and it will also deal some damage to the player to do so, so they can no longer simply delete a dangerous mob
- Certain stronger mobs cannot be shucked at all anymore, to prevent being able to simply delete a dangerous mob. We should have a tag list for this and I can add to it if so
- Returning a mob to the world from a fruit will also consume a blight potion (returning the bottle), and take some health from the player, while also pausing healing
- [ ] **Ympemould changes**
- No longer spawned from an item, and can no longer be picked up and turned into an item
- Update texture to reflect the netherite removals
- Has to be created in-world like the other constructs
- Fix its crusty asf ai
- New sounds
- [ ] **Boss Heart tag**
- Allows assorted items to be deemed "boss hearts". For now this will only contain the Yhondyth Heart and Wither Star, but it will have more uses in the future. Datapack-support
- [ ] **Vital Thurible Nerf**
- Crafted with any Boss Heart instead of an aylythian heart
- [ ] **Aylythian Heart Change**
- Only dropped if the killing blow is dealt by either aylyth dagger
- Double check to make sure they drop? I have been told the drop is broken
- [ ] **Nether-locked dying-entrance**
- Accidently entering the realm through dying in forest biomes now procs if you have been to the nether or aylyth already, preventing really unprepared players from entering an endgame dimension accidently
- Using seeps or hearts will still send you to aylyth, regardless
- Can be toggled, default off (meaning by default you can enter it before visiting the realm or the nether)
- [ ] **Woody Growth Cache Always Generates: **
- Regardless of how you die in the world, any dropped items will be placed in one of these. However if you do die from Branches, just like before it will wear your armour and carry whatever you were holding when you died, just any other items will be placed in the Cache like before.

### Log or crash report

n/a
