### ISSUE TITLE
[Checklist] Major new content

### ISSUE THREAD

**Issue by cybercat5555** [MoriyaShiine/aylyth#77]
### Mod version (NOT Minecraft version)

1.20.1

### A description of the issue

Summary of new content that is not specifically related to worldgen (but might have some association). Many of these are to help flesh out the dim and make it more of a challenge, while also having many interesting progression changes and other reasons to explore (list not complete)

### Weapons/Gear
- [ ] **Heartwood Armour**: A set of armour between iron and diamond, and is created by upgrading iron with an Aylythian Upgrade and Esstline. It protects more vs aylyth mobs and aylyth weapons, and has a secondary effect, which is TBD, but will likely involve damage splitting and healing

- [ ] **Ympe Flamberge**: 
 - Melee: it is primarily designed around taking on enemies with a large amount of health and armour (other than bosses). It uses the following logic to help multiply damage:
   8.5 base damage
   . <30 hp; nothing
   . 30 to 40 hp; + 15% of their HP added as damage
   . >=40 hp; + 25% of their hp added as damage
Regardless of the target’s health, upon crit there is a 50% chance to deal 50% of the damage as armour bypassing
These effects only apply on fully charged hits. Partially charged hits will not use this formula
 - Magic: Its alt attack sends a sphere of sharp branches out, and when they land, they place a tangle of roots that holds enemies in place, allowing for either a means to escape or to prevent the target from escaping
Has a cooldown between uses of the spell
Other Stats
   Durability: same as the other large weapons
   Speed:
   Cooldown:
   Enchantability: 14 (same as iron)

 - [ ] **Ympe Scythe**:
  -  Melee: removes any absorption hearts and turns any Wrongmeat hearts into abs, allowing them all to be removed on the next swing, regardless of the actual damage it does. Has built in sweeping edge also
   Meathearts will be recovered as meathearts after a bit, so fear not
   i.e. If you have 5 meathearts, they get converted to abs, and lose the abs hearts, after 5 min they all restore as 5 meathearts, but will be empty, so you will need to refill them using a Nephite Flask like normal
 - Magic: r-clicking with it swings the weapon, covering it with soulfire, which then creates 5 slow-moving bombs that float towards the nearest target, which if they make contact with anything (other than the caster and other bombs), they explode. The fire on the weapon lingers for a bit (5 sec), or until you hit a mob. They will be burned and take extra magical damage from it
   The bombs have a soulfire aesthetic, but does not burn and does not break blocks
   Based off the Nebula spell from Elden Ring
   Has a cooldown between uses of the spell
Other Stats
Durability: same as the other large weapons
Speed:
Cooldown
Enchantability: 14 (same as iron)

- [x] **Lanceolet Dagger**:
 Cheapo version of the Ympe Dagger
 Created by combining Cobbled Deepslate with a Ympe Sapling in a smithing table, with another Ympe Sapling as the “template”
  Can harvest ympe fruits and bark, collect aylythians hearts, and start fire rituals
  CANNOT harvest wrongmeat or shuck fruits
 
- [ ] **Esstline and The Smoke**: An item vital to progression in the mod, replacing and acting as an alterative to Netherite. Does nothing on its own

###Mob and Mob-Adjacent
- [ ] **The Smoke**: A passive being summoned from Black Wells, via throwing a Ympe Fruit, Grapes, or Pomegranate into it. The mob appears as a pass of smoke with glowing eyes, and does not leave the well (if forcefully moved, it teleports back to it), and will stay present for 2 minutes, before it returns to the well and goes to sleep. It will sleep for 3 days before it can be summoned again. When interacted with, it takes 20% of the player's HP as hard damage, then returns an Esstline. It refuses to trade with you if you are at or below 20% max health (due to other Smoke or similar being trades). The hard damage will recover in 7 in-game days, based on each time it was used.

### Log or crash report

n/a
